#!/usr/bin/env jruby --2.0 -J-cp /usr/local/Cellar/frege/3.21.500-g88270a0/libexec/frege3.21.500-g88270a0.jar:. -S rake

begin
  require "#{dir = File.dirname(__FILE__)}/task/gemgem"
rescue LoadError
  sh 'git submodule update --init'
  exec Gem.ruby, '-S', $PROGRAM_NAME, *ARGV
end

Gemgem.init(dir) do |s|
  s.name    = 'spellbook'
  s.version = '0.0.1'
  %w[].each{ |g| s.add_runtime_dependency(g) }
end
